---

- name: Ensure the grub password is defined
  ansible.builtin.assert:
    that:
      - grub_user is defined
      - grub_password is defined
      - grub_salt is defined

- name: Encrypt password
  ansible.builtin.expect:
    command: "{{ grub_password_tool }} -s {{ grub_salt }}"
    responses:
      Enter password: '{{ grub_password }}'
      Reenter password: '{{ grub_password }}'
  changed_when: false
  no_log: true
  register: _grub_pwd

- name: Get encrypted password
  ansible.builtin.set_fact:
    grub_password_encrypted: >-
      {{ _grub_pwd.stdout_lines | last | regex_replace('.*grub.pbkdf2.sha512', 'grub.pbkdf2.sha512') }}

- name: Create grub file /etc/grub.d/40_custom
  ansible.builtin.blockinfile:
    path: /etc/grub.d/40_custom
    block: |
      set superusers="{{ grub_user }}"
      password_pbkdf2 boot {{ grub_password_encrypted }}
  register: __password_update

- name: Replace CLASS
  ansible.builtin.lineinfile:
    path: /etc/grub.d/10_linux
    regexp: "^CLASS=.*"
    line: "CLASS=\"--class gnu-linux --class gnu --class os --unrestricted\""

- name: Update grub (Debian)
  ansible.builtin.command:
    cmd: update-grub
  changed_when: true
  when:
    - ansible_facts['os_family'] == 'Debian'
    - __password_update is changed

- name: Update grub (RedHat)
  ansible.builtin.command:
    cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
  changed_when: true
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - __password_update is changed
